DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Forums;
DROP TABLE IF EXISTS Threads;
DROP TABLE IF EXISTS Posts;


CREATE TABLE Users
(
  `UsersId` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
  `Username` TEXT NOT NULL UNIQUE,
  `Password` TEXT NOT NULL
);


CREATE TABLE Forums
(
  `ForumsId` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
  `CreatorId` INTEGER NOT NULL,
  `ForumsName` TEXT NOT NULL UNIQUE,
  FOREIGN KEY(`CreatorId`) REFERENCES `Users`(`UsersId`) ON DELETE CASCADE
);


CREATE TABLE Threads
(
  `ThreadsId` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
  `ForumsId` INTEGER NOT NULL,
  `ThreadsTitle` TEXT NOT NULL,
  FOREIGN KEY(`ForumsId`) REFERENCES `Forums`(`ForumsId`) ON DELETE CASCADE
);


CREATE TABLE Posts
(
  `PostsId` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
  `UsersId` INTEGER NOT NULL,
  `PostsTimestamp` TEXT NOT NULL,
  `Message` TEXT NOT NULL,
  FOREIGN KEY(`UsersId`) REFERENCES `Threads`(`UsersId`) ON DELETE CASCADE
);

CREATE INDEX `PostsChronological`
ON `Posts`
(
  `PostsTimestamp` ASC
);

CREATE INDEX `UsersId`
ON `Users`
(
  `usersId` ASC
);

INSERT INTO Users (Username, Password) VALUES ("login", "testpass");
